### ISSUE TITLE
Scope best way to make install `twilio-cli` and the `serverless` plugin.

### ISSUE THREAD

**Issue by Xabadu** [twilio-labs/vscode-twilio#7]

**Comment by RanadeepPolavarapu** [comment]
I can take this.

**Comment by cweems** [comment]
@RanadeepPolavarapu Great! We're hoping to figure out if there's a way once the package is installed to run the following commands:

`npm install twilio-cli -g`
`twilio plugins:install @twilio-labs/plugin-serverless`

**Comment by mkkhedawat** [comment]
@cweems  Have you considered `preinstall` from npm scripts?

**Comment by RanadeepPolavarapu** [comment]
#21 seems to be a cleaner way to do this because it allows user to be notified we are running this on init and if for any reason (path issues as one example) the installation fails, we can tell them they can run it themselves.

This is the typical de-facto standard in how other extensions do this where they need to install/pull some dependency on activation. 

I added a check so the install does not run on every extension activation. 

Example of `npm` with `--json` flag for checking.

![image](https://user-images.githubusercontent.com/7084995/66270682-53912a80-e824-11e9-9588-6259245f53fc.png)
